apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fsi8av0ba-python
  janus-idp.io/tekton: fsi8av0ba-python
  backstage.io/kubernetes-id: fsi8av0ba-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fsi8av0ba-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
