apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fsi8av0ba-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fsi8av0ba-python 
  name: fsi8av0ba-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fsi8av0ba-python 
